openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0

paths:
  /v1/members/me:
    post:
      summary: Get current member
      operationId: GetMe
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Get me success
          headers:
            versionId:
              description: Indicates the response schema version used.
              schema:
                type: string
                example: v1
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/logout:
    post:
      summary: Logout current user
      operationId: Logout
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logout success
          headers:
            versionId:
              description: Indicates the response schema version used.
              schema:
                type: string
                example: v1
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
        refreshToken:
          type: string
          description: Opaque refresh token stored in Redis

    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: string
          example: "invalid credentials"